routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//LA RUTA ESTA ASOCIADA A UN CONTROLADOR Y EL CONTROLADOR RESPONDERA
//CON UNA VISTA
//rutas para acciones a tomar
Route::get('/', 'TestController@welcome');
// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
//se pone de primero para darle prioridad a esta ruta
Route::get('/search' , 'SearchController@search');
Route::get('/products/json' , 'SearchController@data');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/products/{id}','ProductController@show'); //mostrar el producto
Route::get('/categories/{category}','CategoryController@show'); //mostrar categorias
Route::post('/cart','CartDetailController@store'); //carrito de usuarios 
//Route::post('/cartguest','CartDetailController@storeguest'); //carrit de invitados
Route::delete('/cart','CartDetailController@destroy');//eliminar producto del carrito tradiccional
// Route::post('/cart/id','CartDetailController@destroyPlato');//eliminar producto del carrito con jequery-confirm
//para redirigi al registro desde el formulario principal con nombre y correo
// Route::get('/registerinput' , 'RegisterController@showRegistrationForm');

//rutas para confirmar venta por parte del usuario
Route::post('/order','CartController@update');

//aplicar middleware admin para las rutas que puede acceder
//prefix se usa en las ruta el primer atributo
//namespace es para sa segunda columna del get
Route::middleware(['auth','admin'])->prefix('admin')->namespace('Admin')->group(function () {
    Route::get('/products','ProductController@index');//listar todos los productos
    Route::get('/products/create','ProductController@create'); //vista permite crear nuevos productos solo administradores
    Route::post('/products','ProductController@store'); //enviar datos que permite crear nuevos productos solo administradores
    Route::get('/products/{id}/edit','ProductController@edit'); //vista permite edita productos por medio de un id a solo administradores
    Route::post('/products/{id}/edit','ProductController@update'); //enviar datos que permite actualizar productos con una id solo administradores
    Route::delete('/products/{id}','ProductController@destroy'); //vista para eliminar productos

	Route::get('/products/{id}/images', 'ImageController@index'); // listado
	Route::post('/products/{id}/images', 'ImageController@store'); // registrar
	Route::delete('/products/{id}/images', 'ImageController@destroy'); // form eliminar
	Route::get('/products/{id}/images/select/{image}', 'ImageController@select'); // destacar

    //rutas para el crud de categorias
    //paso 1 para crear un CRUD de una tabla
    Route::get('/categories','CategoryController@index');//listar todos los categorias
    Route::get('/categories/create','CategoryController@create'); //vista permite crear nuevos productos solo administradores
    Route::get('/categories/{id}','CategoryController@show'); //mostrar la categoria seleccionada de la lista
    Route::post('/categories','CategoryController@store'); //enviar datos que permite crear nuevos productos solo administradores
    Route::get('/categories/{id}/edit','CategoryController@edit'); //vista permite edita productos por medio de un id a solo administradores
    Route::post('/categories/{id}/edit','CategoryController@update'); //enviar datos que permite actualizar productos con una id solo administradores
    Route::delete('/categories/{id}','CategoryController@destroy'); //vista para eliminar productos
    //
	// Route::get('/categories', 'CategoryController@index'); // listado
	// Route::get('/categories/create', 'CategoryController@create'); // formulario
	// Route::post('/categories', 'CategoryController@store'); // registrar
	// Route::get('/categories/{category}/edit', 'CategoryController@edit'); // formulario edición
	// Route::post('/categories/{category}/edit', 'CategoryController@update'); // actualizar
	// Route::delete('/categories/{category}', 'CategoryController@destroy'); // form eliminar
});

// Route::get('/admin/products','ProductController@index');//listar todos los productos
// Route::get('/admin/products/create','ProductController@create'); //vista permite crear nuevos productos solo administradores
// Route::post('/admin/products','ProductController@store'); //enviar datos que permite crear nuevos productos solo administradores
// Route::get('/admin/products/{id}/edit','ProductController@edit'); //vista permite edita productos por medio de un id a solo administradores
// Route::post('/admin/products/{id}/edit','ProductController@update'); //enviar datos que permite actualizar productos con una id solo administradores
// Route::delete('/admin/products/{id}','ProductController@destroy'); //vista para eliminar productos
// Route::get('','');
// Route::get('','');
// Route::get('','');
// Route::get('','');
// Route::get('','');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $fillable = ['name', 'long_description', 'price', 'category_id'];

    public static $messages = [
        'name.required' => 'El nombre es un campo obligatorio',
        'name.min' => 'El nombre debe tener minimo 3 caracteres',
        'long_description.required' => 'La descripción es un campo obligatorio',
        'long_description.max' => 'La descripcion debe tener maximo 200 caracteres',
        'price.required' => 'El precio es un campo obligatorio',
        'price.numeric' => 'El precio es un campo de solo numeros',
        'price.min' => 'El precio no debe ser menor de cero'
    ];

    public static $rules = [
            'name' => 'required|min:3',
            'long_description' => 'required|max:200',
            'price' => 'required|numeric|min:0'
    ];

    //$product -> Category
    public function category() {
        return $this->belongsTo(Category::class); //1 pdoducto pertene a una categoria
    }

    //$product -> $images
    public function images() {
        return $this->hasMany(ProductImage::class); //1 pdoducto pertene a una categoria
    }

    public function getFeaturedImageUrlAttribute() {
        $featuredImage = $this->images()->where( 'featured' , true ) -> first();
        if( !$featuredImage ) {
            $featuredImage = $this -> images() -> first();
        }
        if( $featuredImage ) {
            return $featuredImage -> url; //url segun la creada en el modelo ProductImage::getUrlAttribute
        }
        //si no entra a ningun if se pone una imagen por defecto
        return '/images/products/default2.jpg';
    }

    //obtener el nombre de la categoria
    public function getCategoryNameAttribute() {
        if( $this -> category ) return $this -> category -> name;
        return 'General';
    }

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;
use App\Category;

class ProductController extends Controller
{

    private $categories;
    //
    public function index() {
        $products = Product::orderBy('id' , 'DESC') -> get(); //para paginar los productos de 15 en 15
        return view('admin.products.index')->with(compact('products')); //listado de productos
    }

    public function create() {
        // $categories = Category::all(); //traer todas las categorias
        $categories = Category::orderBy( 'name' ) -> get(); //traer todas las categorias pero ordenadas por nombre
        return view('admin.products.create') -> with( compact( 'categories' ) ); //formulario de registro de categorias
    }

    public function store( Request $request ) {
        //dd($request->all());//el metodo permite imprimir todos los datos del request
        // return view(); //almacenar el registro de un producto
        //validar datos con reglas de laravel en documentacion hay mas
        //mensajes personalizados para cada campo
        $this->validate($request,Product::$rules,Product::$messages);
        //crear un prodcuto nuevo
        $product = new Product();
        $product -> name = $request->input('name');
        //$product -> description = $request->input('description');
        $product -> price = $request->input('price');
        $product -> long_description = $request->input('long_description');
        $product -> category_id = $request -> input( 'category_id' );
        $product -> save(); //registrar producto
        $notification = 'Producto Agregado Exitosamente';
        return redirect('/admin/products') -> with( compact( 'notification' ) );
    }

    public function edit( $id ) {
//        $categories = Category::all(); //traer categorias
        // return "Mostrar aqui formulario para producto con id $id";
        $product = Product::find( $id );
        $categories = Category::orderBy( 'name' ) -> get(); //traer todas las categorias pero ordenadas por nombre
        return view('admin.products.edit')->with(compact('product','categories')); //formulario de registro
    }

    public function update( Request $request , $id ) {
        //dd($request->all());//el metodo permite imprimir todos los datos del request
        // return view(); //almacenar el registro de un producto
        //validar datos con reglas de laravel en documentacion hay mas
        //mensajes personalizados para cada campo
        $this->validate($request,Product::$rules,Product::$messages);
        //crear producto para actualizar buscandolo por su id
        $product = Product::find( $id );
        $product -> name = $request->input('name');
        //$product -> description = $request->input('description');
        $product -> price = $request->input('price');
        $product -> long_description = $request->input('long_description');
        $product -> category_id = $request -> input( 'category_id' );
        $product -> save(); //actualizar producto

        $notification = 'Producto ' . $request->input('name') . ' Actualizado Exitosamente';
        return redirect('/admin/products') -> with( compact( 'notification' ) );
    }

    public function destroy( $id ) {
//        $categories = Category::all(); //traer categorias
        // return "Mostrar aqui formulario para producto con id $id";
        $product = Product::find( $id );
        $product -> delete(); //ELIMINAR
        $notification = 'Producto ' . $product -> name . ' Eliminado Exitosamente';
        return back() -> with( compact( 'notification' ) ); //nos devuelve a la pagina anterior
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class ProductController extends Controller
{
    //mostrar un prodcuto a un visitante
    public function show( $idProduct ) {
        $product = Product::find( $idProduct );
        $images = $product -> images;
        $imagesLeft = collect();
        $imagesRight = collect();
        foreach ($images as $index => $image) {
            # code...
            if( $index % 2 == 0 ) {
                $imagesLeft -> push( $image );
            }
            else {
                $imagesRight -> push( $image );
            }
        }
        return view('products.show')->with(compact('product','imagesLeft' , 'imagesRight'));
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('title','Registrar Producto')

@section('body-class','profile-page')

@section('content')
<div class="header header-filter" style="background-image: url('{{ asset('img/fondo2.jpg') }}');">

</div>

<div class="main main-raised">
	<div class="container">

    	<div class="section">
            <h2 class="title text-center">Registrar Nuevo Producto</h2>

			<div class="team">
				<div class="row">
                    <!-- Mostrar los errores capturados por validate -->
                    @if ($errors->any())
                    <div class="alert alert-warning">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="post" action="{{ url('/admin/products') }}">
                    {{ csrf_field() }}

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group label-floating">
                                <label class="control-label">Nombre del producto</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group label-floating">
                                <label class="control-label">Precio del producto</label>
                                <input type="number" class="form-control" name="price" value="{{ old('price') }}">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <!-- <div class="col-sm-6">
                             <div class="form-group label-floating">
                                <label class="control-label">Descripción corta</label>
                                <input type="text" class="form-control" name="description" value="{{ old('description') }}">
                            </div>
                        </div> -->

                        <div class="col-sm-4">
                            <div class="form-group label-floating">
                                <label class="control-label">Categoría del producto</label>
                                <select class="form-control" name="category_id">
									<option class="form-control" value="0">General</option>
									@foreach( $categories as $categorie )
										<option value="{{ $categorie -> id }}">{{ $categorie -> name }}</option>
									@endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <textarea class="form-control" placeholder="Descripción extensa del producto" rows="5" name="long_description">{{ old('long_description') }}</textarea>
                        </div>
                    </div>

                    <div class="text-center">
                        <button class="btn btn-danger">Registrar producto</button>
                        <a href="{{ url('/admin/products') }}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
				</div>
			</div>

        </div>

    </div>

</div>

<!-- incluir el footer desde una vista en la carpeta includes -->
@include('includes.footer')
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('title','Registrar Producto')

@section('body-class','profile-page')

@section('content')
<div class="header header-filter" style="background-image: url('{{ asset('img/fondo2.jpg') }}');">

</div>

<div class="main main-raised">
	<div class="container">

    	<div class="section">
            <h2 class="title text-center">Editar Producto {{ $product -> name }}</h2>

			<div class="team">
				<div class="row">
					<!-- Mostrar los errores capturados por validate -->
                    @if ($errors->any())
                    <div class="alert alert-warning">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="post" action="{{ url('/admin/products/'.$product->id.'/edit') }}">
                    {{ csrf_field() }}

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group label-floating">
                                <label class="control-label">Nombre del producto</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name', $product->name) }}">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group label-floating">
                                <label class="control-label">Precio del producto</label>
								<!-- step=0.01 permite guardar numeros flotantes segun los decimales -->
                                <input type="number" step="0.01" class="form-control" name="price" value="{{ old('price', $product->price) }}">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <!-- <div class="col-sm-6">
                             <div class="form-group label-floating">
                                <label class="control-label">Descripción corta</label>
                                <input type="text" class="form-control" name="description" value="{{ old('description', $product->description) }}">
                            </div>
                        </div> -->

						<div class="col-sm-4">
                            <div class="form-group label-floating">
                                <label class="control-label">Categoría del producto</label>
                                <select class="form-control" name="category_id">
									<option class="form-control" value="0" selected>General</option>
									@foreach( $categories as $categorie )
											<option value="{{ $categorie -> id }}" @if( $categorie -> id == old( 'category_id', $product -> category_id ) )  selected @endif>{{ $categorie -> name }}</option>
									@endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <textarea class="form-control" placeholder="Descripción extensa del producto" rows="5" name="long_description">{{ old('long_description',$product->long_description) }}</textarea>
                        </div>
                    </div>



                    <!-- <textarea class="form-control" placeholder="Descripción extensa del producto" rows="5" name="long_description">{{ old('long_description', $product->long_description) }}</textarea> -->
                    <div class="text-center">
                        <button class="btn btn-danger">Actualizar Producto</button>
                        <a href="{{ url('/admin/products') }}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
				</div>
			</div>

        </div>

    </div>

</div>

<!-- incluir el footer desde una vista en la carpeta includes -->
@include('includes.footer')
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('title','Listado de Productos')

@section('styles')

<!-- <link href="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/css/foundation.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.foundation.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.foundation.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.foundation.min.css" rel="stylesheet" /> -->
<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css" rel="stylesheet" /> -->
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.bootstrap4.min.css" rel="stylesheet" />


@endsection

@section('body-class','profile-page')

@section('content')
<div class="header header-filter" style="background-image: url('{{ asset('img/fondo2.jpg') }}');">

</div>

<div class="main main-raised">
	<div class="container">
    	<div class="section text-center">
            <h2 class="title">Lista de Productos</h2>

			<div class="team">
				<div class="row">
					<!-- mostrar mensaje del controlador -->
					@if (session('notification'))
						<div class="alert alert-success">
							<div class="container-fluid">
								<div class="alert-icon">
									<i class="material-icons">check</i>
								</div>
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true"><i class="material-icons">clear</i></span>
								</button>
								{{ session('notification') }}
							</div>
						</div>
		            @endif
                    <a href="{{ url('/admin/products/create') }}" class="btn btn-danger btn-round">Nuevo producto</a>
                    <!-- <br> -->
                    <hr>



                    <table class="table" cellspacing="0" id="tableProducts">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="col-md-2 text-center">Nombre</th>
                                <th class="col-md-4 text-center">Descripción</th>
                                <th class="col-md-2 text-center">Categoría</th>
                                <th class="col-md-1 text-right">Precio</th>
                                <th class="col-md-3 text-right">Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($products as $product)
                            <tr>
                                <td class="text-center">{{ $product->id }}</td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->long_description }}</td>
                                <!-- operador ? para preguntar por un parametro existe si no muesta 'general' -->
                                <!-- <td>{{ $product->category ? $product->category->name : 'General' }}</td> -->
								<td>{{ $product->category_name }}</td>
                                <td class="text-right">$ {{ $product->price }}</td>
                                <td class="td-actions text-right">
                                    <form method="post" action="{{ url('/admin/products/'.$product->id) }}" class="delete">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}

                                        <a href="{{ url('/products/'.$product->id) }}" rel="tooltip" title="Ver producto" class="btn btn-info btn-simple btn-xs">
                                            <i class="fa fa-info"></i>
                                        </a>
                                        <a href="{{ url('/admin/products/'.$product->id.'/edit') }}" rel="tooltip" title="Editar producto" class="btn btn-success btn-simple btn-xs">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a href="{{ url('/admin/products/'.$product->id.'/images') }}" rel="tooltip" title="Imágenes del producto" class="btn btn-warning btn-simple btn-xs">
                                            <i class="fa fa-image"></i>
                                        </a>
                                        <a class='btn btn-danger btn-simple btn-xs' rel="tooltip" title="Eliminar" onclick="Delete('{{ $product -> name }}')"><i class='fa fa-times'></i> </a>
                                        <!-- <button type="submit" rel="tooltip" title="Eliminar" class="btn btn-danger btn-simple btn-xs">
                                            <i class="fa fa-times"></i>
                                        </button> -->
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!-- para mostrar la paginacion hecha en el controlador -->
                    {{--{{ $products -> links() }}--}}
				</div>
			</div>

        </div>
    </div>

</div>

<!-- incluir el footer desde una vista en la carpeta includes -->
@include('includes.footer')
@endsection

@section('scripts')
    <!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script> -->
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script> 
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.1/js/responsive.bootstrap4.min.js"></script>

    <script>
        function Delete( nameProduct ) {
			$.confirm({
				theme: 'supervan',
				title: 'Eliminar Plato',
				content: 'Seguro(a) que deseas eliminar el Plato ' + nameProduct + '. <br> Click Aceptar or Cancelar',
				icon: 'fa fa-question-circle',
				animation: 'scale',
				animationBounce: 2.5,
				closeAnimation: 'scale',
				opacity: 0.5,
				buttons: {
					'confirm': {
						text: 'Aceptar',
						btnClass: 'btn-blue',
						action: function () {
							$.confirm({
								theme: 'supervan',
								title: 'Estas Seguro ?',
								content: 'Una vez eliminado debes volver a crear el plato',
								icon: 'fa fa-warning',
								animation: 'scale',
								animationBounce: 2.5,
								closeAnimation: 'zoom',
								buttons: {
									confirm: {
										text: 'Si, Estoy Seguro!',
										btnClass: 'btn-orange',
										action: function () {
											$('.delete').submit();
										}
									},
									cancel: {
										text: 'No, Cancelar',
										//$.alert('you clicked on <strong>cancel</strong>');
									}
								}
							});
						}
					},
					cancel: {
						text: 'Cancelar',
						//$.alert('you clicked on <strong>cancel</strong>');
					},
				}
			});
		}
    </script>
    <script>
        $(document).ready(function() {
            $('#tableProducts').DataTable({
                "language": {

                    "emptyTable": "No hay productos , click en el boton <b>Nuevo Producto</b> para agregar uno nuevo",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "previous": "Anterior",
                        "next": "Siguiente",
                    },
                    "search": "Buscar: ",
                    "info": "Mostrando del _START_ al _END_, de un total de _TOTAL_ entradas",
                    "lengthMenu": "Mostrar _MENU_ Productos por Página",
                    "zeroRecords": "No se encontro ningun resultado",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                },
                "responsive" : "true",
                "autoWidth": "true"
            });
        });
    </script>
@endsection